# Generated by Django 4.1.7 on 2023-03-10 11:40

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('oneAgo', models.IntegerField(blank=True, null=True)),
                ('twoAgo', models.IntegerField(blank=True, null=True)),
                ('thirdAgo', models.IntegerField(blank=True, null=True)),
                ('fourAgo', models.IntegerField(blank=True, null=True)),
                ('fiveAgo', models.IntegerField(blank=True, null=True)),
                ('sixAgo', models.IntegerField(blank=True, null=True)),
                ('sevenAgo', models.IntegerField(blank=True, null=True)),
                ('eightAgo', models.IntegerField(blank=True, null=True)),
                ('nineAgo', models.IntegerField(blank=True, null=True)),
                ('tenAgo', models.IntegerField(blank=True, null=True)),
                ('elevenAgo', models.IntegerField(blank=True, null=True)),
                ('twelveAgo', models.IntegerField(blank=True, null=True)),
                ('userID', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('oneAgo', models.IntegerField(blank=True, null=True)),
                ('twoAgo', models.IntegerField(blank=True, null=True)),
                ('thirdAgo', models.IntegerField(blank=True, null=True)),
                ('fourAgo', models.IntegerField(blank=True, null=True)),
                ('fiveAgo', models.IntegerField(blank=True, null=True)),
                ('sixAgo', models.IntegerField(blank=True, null=True)),
                ('sevenAgo', models.IntegerField(blank=True, null=True)),
                ('eightAgo', models.IntegerField(blank=True, null=True)),
                ('nineAgo', models.IntegerField(blank=True, null=True)),
                ('tenAgo', models.IntegerField(blank=True, null=True)),
                ('elevenAgo', models.IntegerField(blank=True, null=True)),
                ('twelveAgo', models.IntegerField(blank=True, null=True)),
                ('userID', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('oneAgo', models.IntegerField(blank=True, null=True)),
                ('twoAgo', models.IntegerField(blank=True, null=True)),
                ('thirdAgo', models.IntegerField(blank=True, null=True)),
                ('fourAgo', models.IntegerField(blank=True, null=True)),
                ('fiveAgo', models.IntegerField(blank=True, null=True)),
                ('sixAgo', models.IntegerField(blank=True, null=True)),
                ('sevenAgo', models.IntegerField(blank=True, null=True)),
                ('eightAgo', models.IntegerField(blank=True, null=True)),
                ('nineAgo', models.IntegerField(blank=True, null=True)),
                ('tenAgo', models.IntegerField(blank=True, null=True)),
                ('elevenAgo', models.IntegerField(blank=True, null=True)),
                ('twelveAgo', models.IntegerField(blank=True, null=True)),
                ('userID', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('GasActual', models.IntegerField(blank=True, null=True)),
                ('GasOneAgo', models.IntegerField(blank=True, null=True)),
                ('WaterActual', models.IntegerField(blank=True, null=True)),
                ('WaterOneAgo', models.IntegerField(blank=True, null=True)),
                ('ElectricityActual', models.IntegerField(blank=True, null=True)),
                ('ElectricityOneAgo', models.IntegerField(blank=True, null=True)),
                ('userID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('electricity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.electricity')),
                ('gas', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.gas')),
                ('water', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.water')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('licSchet', models.CharField(max_length=20, unique=True)),
                ('username', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.data')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
